TRI_LAYER_ENABLE = yes

MIDI_ENABLE = no

MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
CRGBLIGHT_ANIMATIONS = no

SPLIT_KEYBOARD = yes

RGBLIGHT_ENABLE = yes
RGBLIGHT_EFFECT_BREATHING = yes
RGBLIGHT_EFFECT_RAINBOW_MOOD = yes
RGBLIGHT_EFFECT_RAINBOW_SWIRL = yes
RGBLIGHT_EFFECT_SNAKE = no
RGBLIGHT_EFFECT_KNIGHT = no
RGBLIGHT_EFFECT_CHRISTMAS = no
RGBLIGHT_EFFECT_STATIC_GRADIENT = no
RGBLIGHT_EFFECT_RGB_TEST = no
RGBLIGHT_EFFECT_ALTERNATING = no
COMMAND_ENABLE = no

NO_ACTION_MACRO = yes
NO_ACTION_FUNCTION = yes

LTO_ENABLE = yes

SRC += cyberpunk_logo.c
